### ISSUE TITLE
Templates?

### ISSUE THREAD

**Issue by ryansolid** [luwes/sinuous-todomvc#1]
Any reason you chose not to use Templates? Is this the more idiomatic way to implement this? Templates seem to be the key to Sinuous great performance, so I was expecting to see them here. Plus I have a personal interest in the general applicability of the approach. Is it just to reduce size?

**Comment by luwes** [comment]
hey @ryansolid, yes I thought in this case it wouldn't be worth the extra bytes. 
A todo list will most likely not get that many items so I thought it would be more important to show it's possible to build this in the lightest way possible. (to compete with Svelte's bundle size ha :)

I'm currently looking into a creating a `tinymap` that might be included in the Sinuous core, no perf goals, smallest working diff algo. Do you have any recommendations for this?
Looking at these libraries but have no clue yet what could work well. Maybe just the bottom part of the current `map` algo. 

- https://github.com/livoras/list-diff
- https://github.com/paldepind/list-difference
- https://github.com/sveltejs/svelte/blob/master/src/runtime/internal/keyed_each.ts#L24

For the Sinuous TodoMVC I mostly borrowed code from your todo implementation and Adam's, thank you 🙇🏻‍♂️
Really great you can just serialize your state in JSON with no conversions in Solid. Also wondered is all state that you init in `createState` then tracked?

**Comment by ryansolid** [comment]
That's fair. I suspected as much. I personally just have an interest in the approach.

I recently took a big hit in size to fix (https://github.com/ryansolid/solid/issues/55). Basically, all S based libraries have this flaw. There sort of are workarounds (hoisting can work in some cases) but nothing I could generalize without getting into big changes to the reactive system (like Subclocks). I found the solution that worked for me. This pretty much puts Solid out of that race. Mind you, it's lower in my priority list (definitely below performance).

Competing with Svelte in size is difficult. You can use a simpler version of the list reconcile algorithm, but generally I've found they don't handle Fragments. You are correct the top section is all shortcut optimization so, in theory, you could cut that all out I do think that the first 2 sections at least of removing common prefix/suffix are probably still worth it as it is a clear linear optimization. Adam has used simpler versions in SArray (but they don't do the DOM manipulation). It might be possible to start from mapS or mapSample cut out the extra stuff and then replace with specific operations. I've looked at libraries like list-diff before, or Web Reflection's [majinbuu](https://github.com/WebReflection/majinbuu), but they are often generalized. It still should be simple as wrapping the whole thing in a computation(closing over the previous state) where get the latest value, and then sample the diff library's execution. But to remove the overhead of how they pass the reordering info around you would probably need to extract the core of it and use for your own purposes. 

More so, it's hard to compete with Svelte is that they aren't that worried about batching, etc.. Their Reactive system is super simplistic but they compensate by using the compiler to reorder execution to ensure consistency. Even if you drop down to a simpler list reconciler, their reactive code is so minimal. They get away with this since it is all localized. Outside of stores (another piece to import in), their reactive system can't escape the boundaries of the Component. This also has reasonable performance considerations.

I still think it's an admirable goal, since people overvalue size to ridiculous degrees. As soon as you add pretty much anything to your implementation you are up to 100kb anyway even if the library code is less than 1kb. And when you look at the corresponding impact on load time it's in the delta of 10kb range that you notice any consistent measurable difference (like 100ms). At which point the performance of the initial render probably has a bigger impact.

Anyway, the `createState` in that case is completely tracked. Generally, the way it works is it defers creating Signals unless the property is accessed inside a computation. So if you don't access certain properties in a tracking context you don't take the overhead. For example, in the JS Framework Benchmark the row id is never made into a signal since it is never accessed in a tracking context.

**Comment by luwes** [comment]
Thanks for the tips Ryan. I'll have a look at that issue 55. Looks quite complex.

I do agree with the size hype, most libraries are in quite a good range besides the most popular ones 😛. React would take 1/3 of the size of our video player.

Right, that makes sense it only tracks when accessed in a computation. That's cool, I like that serialization just works. Might need to create a helper from that functionality 🙂

**Comment by ryansolid** [comment]
Yeah the solutions were complicated but the problem in 55 is actually super common place. All I was trying to do was prevent complete recreation of children when condition of a "if" (or ternary) evaluates to the same conditional branch. The simple solutions caused a ton of unexpected behavior including evaluating dead branches after they had no reason to exist. I'm shocked more people haven't hit this. Maybe they have and just null checked everything. I may be guilty of that myself. But very confusing and unexpected for developers.
